
import Persistencia.Asistencia;
import Persistencia.BaseDatos;
import Persistencia.Curso;
import Persistencia.Estudiante;
import Persistencia.Persona;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author javie
 */
public class Inicio extends javax.swing.JFrame {

    private ArrayList<Persona> persona;
    private ArrayList<Asistencia> asistencia;
    private ArrayList<Curso> curso;
    private String nombre;
    
    public Inicio() {
        initComponents();
        
        persona = new ArrayList<>();
        asistencia = new ArrayList<>();
        curso = new ArrayList<>();
        
        BaseDatos db = new BaseDatos();
        
        /*db.agregarMaestro("Programacion Orientada a Objetos", "Douglas", "Barrios", 80127, "1234");
        db.agregarMaestro("Calculo 1", "Ronald", "Curtiss", 81284, "1234");
        db.agregarMaestro("Fisica 1", "Magda", "Moscoso", 82313, "1234");*/
        
        for(Persona p: db.recogerPersona()){
            persona.add(p);
        }
        
        for(Asistencia a: db.recogerAsistencia()){
            asistencia.add(a);
        }
        
        for(Curso c: db.recogerCurso()){
            curso.add(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        spnCarnet = new javax.swing.JSpinner();
        txtContra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipo.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblTipo.setText("Estudiante");

        spnCarnet.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        spnCarnet.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99999, 1));

        txtContra.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Carnet");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Contraseña");

        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnAgregar.setText("Agregar alumno");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        cmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estudiante", "Maestro" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Seleccione:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Olvide mi contraseña...");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(lblTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spnCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTipo)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnAgregar)
                .addGap(30, 30, 30)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        String tipo = (String)cmbTipo.getSelectedItem();
        
        lblTipo.setText(tipo);
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        NuevoAlumno na = new NuevoAlumno();
                
        na.setLista(persona, asistencia, curso);
        na.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        int carnet = (int)spnCarnet.getValue();
        String contra = (String)txtContra.getText();
        boolean siguiente = true;
        String tipo = (String)cmbTipo.getSelectedItem();
        String type = "";
        Menu menu = new Menu();
        
        for(Persona p: persona){
            
            if((p.getCarnet() == carnet) && (p.getContrasena().equals(contra))){
                siguiente = true;
                nombre = p.getNombre() + " " + p.getApellido();
                if(p instanceof Estudiante){
                    type = "Estudiante";
                }else{
                    type = "Maestro";
                }
                break;
            }else{
                siguiente = false;
            }
        }
        if(siguiente == true){
            if((tipo.equals("Estudiante")) && (type.equals("Estudiante"))){
                menu.setLista(persona, asistencia, curso);
                Menu.nombre = nombre;
                menu.setVisible(true);
                this.setVisible(false);
            }else if((tipo.equals("Maestro")) && (type.equals("Maestro"))){
                Profesor prof = new Profesor();
                prof.setLista(persona, asistencia, curso);
                Profesor.nombre = nombre;
                prof.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "Algun dato erroneo.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Error 101. Datos incorrectos.");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        int carnet = 0;
        boolean op;
        try{
            carnet = Integer.parseInt(JOptionPane.showInputDialog("Ingrese su numero de carnet"));
            op = true;
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Incorrecto. Ingreso un texto.");
            op = false;
        }
        
        String respuesta;
        String contra = "";
        boolean op1 = false;
        boolean a = true;
        
        if(op == true){
            for(Persona p: persona){
                if(p.getCarnet() == carnet){
                    respuesta = JOptionPane.showInputDialog("Responda:\n" + p.getPregunta());
                    
                    if(respuesta.equals(p.getRespuesta())){
                        op1 = true;
                        contra = p.getContrasena();
                        break;
                    }else{
                        a = true;
                        break;
                    }
                }else{
                    a = false;
                    
                }
            }
        }
        if(op1 == true){
            JOptionPane.showMessageDialog(this, "Carnet: " + carnet + "\nContraseña: " + contra);
        }else if(a == true){
            JOptionPane.showMessageDialog(this, "Respuesta incorrecta.");
        }else if(a == false){
            JOptionPane.showMessageDialog(this, "No se ha encontrado el carnet.");
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    public void setLista(ArrayList<Persona> p, ArrayList<Asistencia> a, ArrayList<Curso> c){
        persona = p;
        asistencia = a;
        curso = c;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSpinner spnCarnet;
    private javax.swing.JPasswordField txtContra;
    // End of variables declaration//GEN-END:variables
}
