
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class NuevoAlumno extends javax.swing.JFrame {

    /**
     * Creates new form NuevoAlumno
     */
    private String nombre;
    private String apellido;
    private String carnet;
    private String contra;
    private String correo;
    private int control;
    private ArrayList<String> correos;
    private ArrayList<String> contrasena;
    private ArrayList<String> nombres;
    private ArrayList<String> apellidos;
    private ArrayList<String> carnets;
    
    public NuevoAlumno() {
        initComponents();
        control = 0;
        nombres = new ArrayList<String>();
        apellidos = new ArrayList<String>();
        carnets = new ArrayList<String>();
        contrasena = new ArrayList<String>();
        correos = new ArrayList<String>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreo = new javax.swing.JTextField();
        lblContacto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtCarnet = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblPuesto = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        lblContacto.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblContacto.setText("Correo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Nuevo Usuario");

        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        txtCarnet.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        lblPuesto.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblPuesto.setText("Apellido");

        lblApellidos.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblApellidos.setText("Password");

        lblNombres.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblNombres.setText("Carnet");

        lblCodigo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblCodigo.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigo)
                    .addComponent(lblPuesto)
                    .addComponent(lblNombres)
                    .addComponent(lblApellidos)
                    .addComponent(lblContacto))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuesto))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContacto)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        InicioSesion inicio = new InicioSesion();
        
        
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        carnet = txtCarnet.getText();
        contra = txtPassword.getText();
        correo = txtCorreo.getText();
        
        if(!nombre.isEmpty()){
            control = control + 1;
        }else{
            JOptionPane.showMessageDialog(this, "No ingreso ningun usuario.");
        }
        
        if((!apellido.isEmpty())){
            control = control + 1;
        }else{
            JOptionPane.showMessageDialog(this, "No ingreso ninguna contrasena");
            control = 0;
        }
        
        if((!carnet.isEmpty())){
            control = control + 1;
        }else{
            JOptionPane.showMessageDialog(this, "No ingreso ningun numero de carnet");
            control = 0;
        }
        
        if((!contra.isEmpty())){
            control = control + 1;
        }else{
            JOptionPane.showMessageDialog(this, "No ingreso ninguna contrasena");
            control = 0;
        }
        
        if((!correo.isEmpty())){
            control = control + 1;
        }else{
            JOptionPane.showMessageDialog(this, "No ingreso ningun correo");
            control = 0;
        }
        
        if(control == 5){
            nombres.add(nombre);
            apellidos.add(apellido);
            carnets.add(carnet);
            contrasena.add(contra);
            correos.add(correo);
            inicio.getInfo(nombres, apellidos, carnets, contrasena, correos);
            inicio.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    public void getArrayLists(ArrayList nom, ArrayList ape, ArrayList car, ArrayList contra, ArrayList cor){
        nombres = nom;
        apellidos = ape;
        carnets = car;
        contrasena = contra;
        correos = cor;
    }
    
    public void limpiarcajas(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtCarnet.setText("");
        txtPassword.setText("");
        txtCorreo.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
